MicrofyWebApp/Models/AuditViewModel.cs
using System.Collections.Generic;

namespace MicrofyWebApp.Models
{
    public class AuditViewModel
    {
        public string projectname { get; set; }
        public string customername { get; set; }
        public ProjectViewModel project { get; set; }
        public List<string> ListUsers { get; set; }
        public List<string> ListAuditor { get; set; }
        public List<ChecklistConfig> Configuration { get; set; }
        public ProjectDetails ProjectDetails { get; set; }
        public List<BestPractice> BestPractices { get; set; }
        public List<Azuretech> AzureServicesUsed { get; set; }
        public List<Observations> Observations { get; set; }
        public List<ActionItems> ActionItems { get; set; }
        public List<Deliverables> Deliverables { get; set; }
        public string Status { get; set; }
        public List<AuditChecklistModel> AuditChecklistModel { get; set; }

    }
    public class SolutionObservationFormInputData
    {
        public ProjectDetails ProjectDetails { get; set; }
        public string UserId { get; set; }
        public string projectname { get; set; }
        public string customername { get; set; }

        public List<Observations> observation { get; set; }
        public List<ActionItems> ActionItems { get; set; }
        public List<BestPractice> Checklist { get; set; }
        public string Status { get; set; }
        public string ProductCategory { get; set; }
        public string Service { get; set; }

    }
    public class Observations
    {
        public string ImpactArea { get; set; }
        public string Observation { get; set; }
    }
    public class ActionItems
    {
        public string ImpactArea { get; set; }
        public string Severity { get; set; }
        public string Concern { get; set; }
        public string RecommendedMitigation { get; set; }
    }
    public class ProjectDetails
    {
        public string ProjectName { get; set; }
        public string CustomerName { get; set; }
        public string CustomerOverview { get; set; }
        public string ProjectOverview { get; set; }
        public string ProjectDeliverables { get; set; }
        public string ProjectStartDate { get; set; }
        public string TentativeEndDate { get; set; }
        public string ApplicationArchitecture { get; set; }
        public string TechnologiesInUse { get; set; }
        public List<Azuretech> AzureServicesUsed { get; set; }
    }
    public class Azuretech
    {
        public string ProductCategory { get; set; }
        public string Services { get; set; }
    }
    public class AuditChecklistModel
    {
        public ProjectDetails ProjectDetails { get; set; }
        public List<BestPractice> Checklist { get; set; }
        public List<Observations> Observations { get; set; }
        public List<ActionItems> ActionItems { get; set; }
        public string UserId { get; set; }
        public string Status { get; set; }
    }
    public class BestPractice
    {
        public string Service { get; set; }
        public List<Section> BestPractices { get; set; }
    }
    public class Section
    {
        public string ImpactArea { get; set; }
        public List<Checklist> Checklist { get; set; }
    }
    public class Checklist
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public Inputvalue Input { get; set; }
        public DisplayAttributes DisplayAttributes { get; set; }

    }
    public class Inputvalue
    {
        public string Title { get; set; }
        public string Value { get; set; }
        public string Remarks { get; set; }

    }
    public class DisplayAttributes
    {
        public string Mandatory { get; set; }
        public string Field { get; set; }
        public string ListOfValues { get; set; }
    }
    public class NavtabParam
    {
        public string projectName { get; set; }
        public string customerName { get; set; }

        public string prevProdCat { get; set; }
        public string prevService { get; set; }
        public string prevDivid { get; set; }
        public string currentProdCat { get; set; }
        public string currentService { get; set; }
        public string currentDivid { get; set; }
    }
    public class Summary
    {
        public string projectname { get; set; }
        public string customername { get; set; }
        public string RequiredCount { get; set; }
        public string NotImplementedCount { get; set; }
        public string ObservationCount { get; set; }
        public string ActionItemsCount { get; set; }
    }
    public class Deliverables
    {
        public string Name { get; set; }
    }
    public class DeliverablesList
    {
        public List<Deliverables> Deliverables { get; set; }
    }
    public class ServiceResponse
    {
        public bool isSuccess { get; set; }
        public string data { get; set; }
        public string exception { get; set; }
    }
}

MicrofyWebApp/Models/ProjectViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MicrofyWebApp.Models
{
    public class ProjectViewModel
    {
        public string responseMessage { get; set; }

        public string ProjectName { get; set; }

        public string CustomerName { get; set; }

        public string Auditor { get; set; }
        //public List<string> Users { get; set; }
        public string CreatedUserId { get; set; }

        public bool StatusCode { get; set; }

        public string Status { get; set; }
        public List<AuditChecklistModel> SolutionObservations { get; set; }
        public string flag { get; set; }


    }

    public class AzureTech
    {
        public string ServiceName { get; set; }

    }
    public class Servicelist
    {
        public List<AzureTech> services { get; set; }
    }
    public class ProjectView
    {
        public List<ProjectViewModel> ProjectsList { get; set; }
        public List<string> Services { get; set; }
        public List<string> ListUsers { get; set; }
        public List<string> ListAuditor { get; set; }

    }
}

MicrofyWebApp/Controllers/ChecklistController.cs
using MicrofyWebApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;

namespace MicrofyWebApp.Controllers
{
    public class ChecklistController : Controller
    {
        private readonly ILogger<ChecklistController> _logger;

        string Asseturl = string.Empty;
        string AssetCode = string.Empty;
        string SolutionObserBaseUrl = string.Empty;
        string SolutionObserCode = string.Empty;
        private IConfiguration _configuration;
        string Userurl = string.Empty;
        string Usercode = string.Empty;
        string userid = string.Empty;
        string bestpracFolder = string.Empty;
        string ChecklistconfigUrl = string.Empty;
        string ChecklistconfigCode = string.Empty;
        string ChecklistDeliverablesfile = string.Empty;

        public ChecklistController(ILogger<ChecklistController> logger, IConfiguration configuration)
        {
            _logger = logger;
            _configuration = configuration;
            Asseturl = _configuration.GetValue<string>("Values:AssetStrgeBaseUrl");
            AssetCode = _configuration.GetValue<string>("Values:AssetStrgeCode");
            SolutionObserBaseUrl = _configuration.GetValue<string>("Values:SolutionObserBaseUrl");
            SolutionObserCode = _configuration.GetValue<string>("Values:SolutionObserCode");
            Userurl = _configuration.GetValue<string>("Values:UsersBaseUrl");
            Usercode = _configuration.GetValue<string>("Values:UsersCode");
            bestpracFolder = _configuration.GetValue<string>("Values:ServiceFolder");
            ChecklistconfigUrl = _configuration.GetValue<string>("Values:ChecklistconfigUrl");
            ChecklistconfigCode = _configuration.GetValue<string>("Values:ChecklistconfigCode");
            ChecklistDeliverablesfile = _configuration.GetValue<string>("Values:ChecklistDeliverables");


        }
        public async Task<UserViewModel> ListAllUsersAsync()
        {
            userid = HttpContext.Session.GetString("_userId");
            string authKey = HttpContext.Session.GetString("_AuthKey");

            UserViewModel userViewModel = new UserViewModel();
            string userResponse = string.Empty;
            string Requestapi = $"api/GetUserList?{Usercode}";

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Userurl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                client.DefaultRequestHeaders.Add("Authorization", authKey);
                HttpResponseMessage Res = await client.GetAsync(Requestapi);
                if (Res.IsSuccessStatusCode)
                {
                    userResponse = Res.Content.ReadAsStringAsync().Result;
                    userViewModel.usersDetails = JsonConvert.DeserializeObject<List<ListUserDetails>>(value: userResponse);
                }

            }
            return userViewModel;
        }



        public string GetMasterTemplate(string mastertemplate, string foldername = null)
        {
            string folder = $"folder={foldername}";
            string template = string.Empty;
            string Requestapi = $"api/GetTemplate/{mastertemplate}?{AssetCode}&{folder}";
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Asseturl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                Task<HttpResponseMessage> response = client.GetAsync(Requestapi);
                HttpResponseMessage file = new HttpResponseMessage();
                file = response.Result;
                template = file.Content.ReadAsStringAsync().Result;
            }

            return template;
        }

        public string GetSolutionObsDetailsAsync(string ProjectName)
        {
            string Requestapi = $"api/GetProjectDetails/{ProjectName}?{SolutionObserCode}";
            string SolObs = string.Empty;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(SolutionObserBaseUrl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                Task<HttpResponseMessage> response = client.GetAsync(Requestapi);
                HttpResponseMessage resp = new HttpResponseMessage();
                resp = response.Result;
                if (resp.IsSuccessStatusCode)
                {
                    SolObs = resp.Content.ReadAsStringAsync().Result;
                }
            }
            return SolObs;
        }



        public string GetProjectDetails(string Projectname)
        {
            string projDet = string.Empty;
            string Requestapi = $"api/GetProjectDetails/{Projectname}?{SolutionObserCode}";
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(SolutionObserBaseUrl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                Task<HttpResponseMessage> response = client.GetAsync(Requestapi);
                HttpResponseMessage resp = new HttpResponseMessage();
                resp = response.Result;
                if (resp.IsSuccessStatusCode)
                    projDet = resp.Content.ReadAsStringAsync().Result;
            }

            return projDet;
        }

        public string GetAllProjectDetails()
        {
            string projDet = string.Empty;
            string Requestapi = $"api/GetAllProjects?{SolutionObserCode}";
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(SolutionObserBaseUrl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                Task<HttpResponseMessage> response = client.GetAsync(Requestapi);
                HttpResponseMessage resp = new HttpResponseMessage();
                resp = response.Result;
                if (resp.IsSuccessStatusCode)
                    projDet = resp.Content.ReadAsStringAsync().Result;
            }

            return projDet;
        }
        public string GetChecklistConfig()
        {
            string config = string.Empty;
            string Requestapi = $"api/GetChecklistConfig?{ChecklistconfigCode}";
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(ChecklistconfigUrl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                Task<HttpResponseMessage> response = client.GetAsync(Requestapi);
                HttpResponseMessage resp = new HttpResponseMessage();
                resp = response.Result;
                if (resp.IsSuccessStatusCode)
                    config = resp.Content.ReadAsStringAsync().Result;
            }

            return config;
        }






        [HttpPost]
        public async Task<ServiceResponse> InsertBestPractices(string data)
        {
            BestPracticesFormInputData dataele = JsonConvert.DeserializeObject<BestPracticesFormInputData>(data);
            ProjectViewModel auditChecklist = new ProjectViewModel();
            ServiceResponse resp = new ServiceResponse();
            AuditViewModel audit = new AuditViewModel();
            Configurations configurations = new Configurations();
            List<BestPractices> bplist = new List<BestPractices>();


            configurations = JsonConvert.DeserializeObject<Configurations>(GetChecklistConfig());
            var configfile = string.Empty;
            foreach (var con in configurations.Configuration)
            {
                if (con.ProductCategory == dataele.ProductCategory)
                {
                    foreach (var ser in con.Services)
                    {
                        if (ser.Name == dataele.Service)
                        {
                            configfile = ser.FileName;
                        }
                    }
                }
            }
            BestPractices bp = new BestPractices();
            var bestPrac = GetMasterTemplate(configfile, bestpracFolder);
            bp = JsonConvert.DeserializeObject<BestPractices>(bestPrac);
            bplist.Add(bp);

            string checklist = GetSolutionObsDetailsAsync(dataele.ProjectName);

            string Requestapi = $"api/UpdateProject?{SolutionObserCode}";

            if (checklist != "")
            {
                auditChecklist = JsonConvert.DeserializeObject<ProjectViewModel>(checklist);
            }

            foreach (var BestPrac in bplist)
            {
                foreach (var sec in BestPrac.Section.Where(x => x.Checklist != null).ToList())
                {
                    var section = from x in sec.Checklist
                                  join y in dataele.Checklist
                                      on new { a = BestPrac.Service, b = sec.ImpactArea, c = x.Title } equals new { a = y.Service, b = y.ImpactArea, c = y.Title }
                                  select new { x, y };

                    foreach (var match in section)
                    {

MicrofyWebApp/Views/Checklist/EditProject.cshtml
@model MicrofyWebApp.Models.AuditViewModel
@{
    var status = "";
    ViewData["Title"] = "Application";
    var applname = string.Empty;
    var custname = string.Empty;
    var auditor = string.Empty;
    List<string> multiuserVal = new List<string>();
    var flag = "Save";
    if (Model.project != null)
    {
        applname = Model.project.ProjectName;
        custname = Model.project.CustomerName;
        auditor = Model.project.Auditor;
        multiuserVal = Model.project.Users;
        flag = "Update";
    }
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Welcome to Cumulus</title>
    <link rel="stylesheet" href="~/lib/jquery/dist/css/jquery-confirm.css" />

    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">


    <!-- jQuery library file -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" src='https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.3.min.js'></script>
    @*<script type="text/javascript" src='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/js/bootstrap.min.js'></script>
        <link rel="stylesheet" media="screen" href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/css/bootstrap.min.css' />*@


    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/dist/jquery-confirm.js"></script>

</head>
<style type="text/css">

    .justify-content-lg-center {
        justify-content: left !important;
    }

    .input-group-addon {
        padding: 6px 20px !important;
    }

    .dropdown-toggle::after {
        display: inline-block;
        margin-left: -0.5em !important;
        margin-bottom: 0.1em !important;
        vertical-align: -0.01em !important;
        content: "";
        border-top: 0.3em solid;
        border-right: 0.3em solid transparent;
        border-bottom: 0;
        border-left: 0.3em solid transparent;
    }
</style>
<body>
    <div class="container-fluid" style="margin-left:15px;">

        <div id="divbreadcrumb" style="padding-bottom:5px;">
            <ol class="breadcrumb breadcrumb-arrow">
                <li class="homelink"><a href="~/Home/Dashboard">Home</a></li>
                <li class="active"><span>Application</span></li>
            </ol>
        </div>
        <div class="content">
            <div>
                <form class="well form-horizontal" action=" " method="post" id="UpdateProjectList_form">
                    <fieldset>
                        <div class="form-group">
                            <label class="col-md-4 control-label"><span style="color:red;">*</span> Application Name</label>
                            <div class="col-md-4 inputGroupContainer">
                                <div class="input-group">
                                    <input name="projectname" id="projectname" placeholder="Application Name" class="form-control" value="@applname">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label"><span style="color:red;">*</span> Customer Name</label>
                            <div class="col-md-4 inputGroupContainer">
                                <div class="input-group">
                                    <input name="customername" id="customername" placeholder="Customer Name" class="form-control" type="text" required value="@custname">
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-4 control-label"><span style="color:red;">*</span> Users</label>
                            <div class="col-md-4 inputGroupContainer">
                                <select multiple="multiple" id="users" class="form-control selectpicker  multiselect" data-live-search="true" data-field="multiselect">
                                    @foreach (var item in Model.ListUsers)
                                    {
                                        @if (multiuserVal.Count > 0)
                                        {
                                            if (multiuserVal.Contains(item))
                                            {
                                                <option value="@item" selected>@item</option>
                                            }
                                            else
                                            {
                                                <option value="@item">@item</option>
                                            }
                                        }
                                        else
                                        {
                                            <option value="@item">@item</option>
                                        }
                                    }
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-4 control-label"><span style="color:red;">*</span>  Solution Collaborator</label>
                            <div class="col-md-4 inputGroupContainer">
                                <div class="input-group">
                                    <select id="auditor" class="col-md-12 form-control selectpicker ">
                                        <option value="">Select</option>
                                        @foreach (var item in Model.ListAuditor)
                                        {
                                            if (auditor.Equals(item))
                                            {
                                                <option value="@item" selected>@item</option>
                                            }
                                            else
                                            {
                                                <option value="@item">@item</option>
                                            }
                                        }
                                    </select>
                                </div>
                            </div>
                        </div>

                        <!-- Button -->
                        <div class="form-group">
                            <div class="col-md-7 control-label ">
                                <button type="submit" id="btnsave" style="display:block;" class="btn btn-primary pull-right" data-flag="@flag"><i class="fa fa-save"></i> Save</button>
                            </div>
                        </div>

                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</body>

</html>
<script type="text/javascript">
           $(document).ready(function () {
                $('#users.multiselect').multiselect({
                   includeSelectAllOption: true,
                   buttonWidth: '180px'
               });
                $('.multiselect.dropdown-toggle').click(function(){
                if($('.multiselect-container').hasClass('show'))
                    $('.multiselect-container').removeClass('show');
                else
                    $('.multiselect-container').addClass('show');
                });


           $("#btnsave").click(function () {
                   var projectname = $('#projectname').val();
                   var customername = $('#customername').val();
                   var users = $('#users').val();
                   var auditor=$('#auditor').val();

                   if(projectname==""){
                        $.alert({
                           title: "Error",
                           content: "Enter Application Name",
                           type: "red"
                       });
                       return false;
                   }
                   if(customername==""){
                        $.alert({
                           title: "Error",
                           content: "Enter Customer Name",
                           type: "red"
                       });
                       return false;
                   }
                   if(users==""){
                        $.alert({
                           title: "Error",
                           content: "Select Users",
                           type: "red"
                       });
                       return false;
                   }
                   if(auditor==""){
                        $.alert({
                           title: "Error",
                           content: "Select Solution Collaborator",
                           type: "red"
                       });
                       return false;
                   }
                   var ProjectDetails = {
                   "ProjectName": projectname,
                   "CustomerName": customername,
                   "Auditor": auditor,
                   "Users": users,
                   "flag":$(this).data("flag")
                   }
                   var redirecturl = "/Checklist/UpdateProject";
               $.post(redirecturl, { "project": ProjectDetails }, function (data) {
                   var title = "";
                   var type = "";
                   var content="";
                   if (data.statusCode == true) {
                       title = "Success!!";
                       type = "green";
                       content="Application created successfully";
                   }
                   else {
                       title = "Error!!";
                       type = "red";
                       content=data.responseMessage;
                   }
                   $.alert({
                           title: title,
                           content: content,
                           type: type,
                           onAction: function () {
                               window.location.href = '@Url.Action("Project","Checklist")';
                           }
                       });
               })
               .fail(function (response) {
                   $.alert({
                       title: 'Error!!',
                       content: response,
                       alignMiddle: true,
                       type: 'red'
                   });
               });
               return false;
       });
    });

               function reset(){
                   $('#projectname').val("");
                 $('#customername').val("");
                 $('#users').val("");
                 $('#auditor').val("");
               }
</script>