MicrofyWebApp/Controllers/ApplicationController.cs
using MicrofyWebApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.tool.xml;
using iTextSharp.text.html.simpleparser;

namespace MicrofyWebApp.Controllers
{
    public class ApplicationController : Controller
    {
        private readonly ILogger<ApplicationController> _logger;

        string Asseturl = string.Empty;
        string AssetCode = string.Empty;
        string SolutionObserBaseUrl = string.Empty;
        string SolutionObserCode = string.Empty;
        private IConfiguration _configuration;
        string Userurl = string.Empty;
        string Usercode = string.Empty;
        string userid = string.Empty;
        string bestpracFolder = string.Empty;
        string configUrl = string.Empty;
        string configCode = string.Empty;
        string ChecklistDeliverablesfile = string.Empty;
        string ApplicationContainer = string.Empty;

        public ApplicationController(ILogger<ApplicationController> logger, IConfiguration configuration)
        {
            _logger = logger;
            _configuration = configuration;
            Asseturl = _configuration.GetValue<string>("Values:AssetStrgeBaseUrl");
            AssetCode = _configuration.GetValue<string>("Values:AssetStrgeCode");
            SolutionObserBaseUrl = _configuration.GetValue<string>("Values:SolutionObserBaseUrl");
            SolutionObserCode = _configuration.GetValue<string>("Values:SolutionObserCode");
            Userurl = _configuration.GetValue<string>("Values:UsersBaseUrl");
            Usercode = _configuration.GetValue<string>("Values:UsersCode");
            bestpracFolder = _configuration.GetValue<string>("Values:ServiceFolder");
            configUrl = _configuration.GetValue<string>("Values:ConfigBaseUrl");
            configCode = _configuration.GetValue<string>("Values:ConfigCode");
            ChecklistDeliverablesfile = _configuration.GetValue<string>("Values:ChecklistDeliverables");
            ApplicationContainer = _configuration.GetValue<string>("Values:ApplicationContainer");


        }
        public async Task<UserViewModel> ListAllUsersAsync()
        {
            userid = HttpContext.Session.GetString("_userId");
            string authKey = HttpContext.Session.GetString("_AuthKey");

            UserViewModel userViewModel = new UserViewModel();
            string userResponse = string.Empty;
            string Requestapi = $"api/GetUserList?{Usercode}";

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Userurl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                client.DefaultRequestHeaders.Add("Authorization", authKey);
                HttpResponseMessage Res = await client.GetAsync(Requestapi);
                if (Res.IsSuccessStatusCode)
                {
                    userResponse = Res.Content.ReadAsStringAsync().Result;
                    userViewModel.usersDetails = JsonConvert.DeserializeObject<List<ListUserDetails>>(value: userResponse);
                }

            }
            return userViewModel;
        }



        public string GetDeliverables()
        {
            string deliverables;
            string Requestapi = $"api/GetDeliverableListFunction?{configCode}";
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(configUrl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                Task<HttpResponseMessage> response = client.GetAsync(Requestapi);
                HttpResponseMessage file = new HttpResponseMessage();
                file = response.Result;
                deliverables = file.Content.ReadAsStringAsync().Result;
            }

            return deliverables;
        }

        public string GetSolutionObsDetailsAsync(string projectname, string customername)
        {
            string ProjectName = "ProjectName=" + projectname;
            string CustomerName = "CustomerName=" + customername;
            string Requestapi = $"api/GetProjectDetails?{SolutionObserCode}&{ProjectName}&{CustomerName}";

            string SolObs = string.Empty;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(SolutionObserBaseUrl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                Task<HttpResponseMessage> response = client.GetAsync(Requestapi);
                HttpResponseMessage resp = new HttpResponseMessage();
                resp = response.Result;
                if (resp.IsSuccessStatusCode)
                {
                    SolObs = resp.Content.ReadAsStringAsync().Result;
                }
            }
            return SolObs;
        }



        public string GetProjectDetails(string Projectname, string customername)
        {
            string ProjectName = "ProjectName=" + Projectname;
            string CustomerName = "CustomerName=" + customername;
            string projDet = string.Empty;
            string Requestapi = $"api/GetProjectDetails?{SolutionObserCode}&{ProjectName}&{customername}";
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(SolutionObserBaseUrl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                Task<HttpResponseMessage> response = client.GetAsync(Requestapi);
                HttpResponseMessage resp = new HttpResponseMessage();
                resp = response.Result;
                if (resp.IsSuccessStatusCode)
                    projDet = resp.Content.ReadAsStringAsync().Result;
            }

            return projDet;
        }

        public string GetAllProjectDetails()
        {
            string projDet = string.Empty;
            string UserId = "UserId=" + HttpContext.Session.GetString("_username");
            string UserRole = "UserRole=" + HttpContext.Session.GetString("_UserRole");
            string Requestapi = $"api/GetAllProjects?{SolutionObserCode}&{UserId}&{UserRole}";
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(SolutionObserBaseUrl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                Task<HttpResponseMessage> response = client.GetAsync(Requestapi);
                HttpResponseMessage resp = new HttpResponseMessage();
                resp = response.Result;
                if (resp.IsSuccessStatusCode)
                    projDet = resp.Content.ReadAsStringAsync().Result;
            }

            return projDet;
        }
        public string GetAzureProductsAndServicesList()
        {
            string config = string.Empty;
            string Requestapi = $"api/GetAzureProductsAndServicesListFunction?{configCode}";
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(configUrl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                Task<HttpResponseMessage> response = client.GetAsync(Requestapi);
                HttpResponseMessage resp = new HttpResponseMessage();
                resp = response.Result;
                if (resp.IsSuccessStatusCode)
                    config = resp.Content.ReadAsStringAsync().Result;
            }

            return config;
        }

        public string GetBestPractices(string service)
        {
            string config = string.Empty;
            string Requestapi = $"api/GetBestPracticesByServiceFunction/{service}?{configCode}";
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(configUrl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                Task<HttpResponseMessage> response = client.GetAsync(Requestapi);
                HttpResponseMessage resp = new HttpResponseMessage();
                resp = response.Result;
                if (resp.IsSuccessStatusCode)
                    config = resp.Content.ReadAsStringAsync().Result;
            }

            return config;
        }

        public string GetServiceByProductCategory(string prodcat, string flag = null)
        {
            string Flag = "Flag=" + flag;
            string config = string.Empty;
            string Requestapi = $"api/GetServiceByProductCategory/{prodcat}?{configCode}&{Flag}";
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(configUrl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                Task<HttpResponseMessage> response = client.GetAsync(Requestapi);
                HttpResponseMessage resp = new HttpResponseMessage();
                resp = response.Result;
                if (resp.IsSuccessStatusCode)

MicrofyWebApp/Views/Shared/VW_CHECKLIST.cshtml
@model MicrofyWebApp.Models.AuditViewModel
@using Newtonsoft.Json
@using System.Text.RegularExpressions
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@{
    string FirstPanel = string.Empty;
    string LastPanel = string.Empty;
    string isactivenav = "active";
    var prevProdCat = string.Empty;
    var prevService = string.Empty;
    var prevDivid = string.Empty;

    var role = HttpContextAccessor.HttpContext.Session.GetString("_UserRole");
    var displaymode = "";
    var disabledmode = "";
    if (role == "User")
    {
        displaymode = "readonly";
        disabledmode = "disabled";
    }
   
}
<style type="text/css">
    .tab-content {
        /*position: absolute;
                                                    width: 450px;*/
        height: auto;
        /*margin-top: -50px;*/
        background: #fff;
        color: #000;
        /*border-radius: 30px;*/
        z-index: 1000;
        box-shadow: 0px 1px 5px rgba(0, 0, 0, 0.4);
        padding: 20px;
        margin-bottom: 50px;
        margin-left: 15px;
    }

        .tab-content button {
            border-radius: 15px;
            width: 100px;
            margin: 0 auto;
            float: right;
        }
</style>
@if (Model.AzureServicesUsed != null)
{
    <div class="rounded shadow ml-3 pt-2 ">
        <ul class="nav nav-tabs nav-pills flex-column flex-sm-row text-center bg-light border-0 " style="font-size:x-small" id="nav-tab" role="tablist">
            @foreach (var mod in Model.AzureServicesUsed.Select((value, i) => new { i, value }))
            {
                FirstPanel = Model.AzureServicesUsed.First().Services;
                isactivenav = string.Empty;
                if (FirstPanel == mod.value.Services)
                {
                    isactivenav = "active";
                }
                var NavParam = new Models.NavtabParam();
                NavParam.projectName = Model.projectname;
                NavParam.customerName = Model.customername;
                NavParam.prevProdCat = prevProdCat;
                NavParam.prevService = prevService;
                NavParam.prevDivid = prevDivid;
                NavParam.currentProdCat = mod.value.ProductCategory;
                NavParam.currentService = mod.value.Services;
                NavParam.currentDivid = mod.value.Services.Substring(0, 3).Replace(" ", "") + "_" + mod.i.ToString();
                var paramter = JsonConvert.SerializeObject(NavParam);
                <li class="nav-item flex-sm">
                    <a class="nav-link border-0 text-uppercase font-weight-bold  @isactivenav" data-prodcat="@mod.value.ProductCategory" data-service="@mod.value.Services" data-div="@NavParam.currentDivid" onclick="LoadService('@paramter','@displaymode')" role="tab" aria-controls="Repository" aria-selected="true" data-toggle="tab" href="#@mod.value.Services.Substring(0, 3).Replace(" ", "")_@mod.i">@mod.value.Services</a>
                </li>
                prevProdCat = mod.value.ProductCategory;
                prevService = mod.value.Services;
                prevDivid = mod.value.Services.Substring(0, 3).Replace(" ", "") + "_" + mod.i.ToString();
            }

        </ul>

    </div>
    <div class="tab-content" id="bestPracDiv">
        @foreach (var mod in Model.AzureServicesUsed.Select((value, i) => new { i, value }))
        {
            FirstPanel = Model.AzureServicesUsed.First().Services;
            isactivenav = string.Empty;
            if (FirstPanel == mod.value.Services)
            {
                isactivenav = "active show";
            }

            <div id="@mod.value.Services.Substring(0, 3).Replace(" ", "")_@mod.i" role="tabpanel" aria-labelledby="@mod.value.Services.Substring(0, 3).Replace(" ", "")_@mod.i-tab" class="tab-pane py-3 fade @isactivenav" data-prodcat="@mod.value.ProductCategory" data-services="@mod.value.Services">

                @foreach (var inp in Model.BestPractices)
                {
                    if (inp.Service == mod.value.Services)
                    {
                        foreach (var ipsection in inp.BestPractices.Select((value, i) => new { i, value }))
                        {
                            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                                <div class="panel panel-default">
                                    <div class="panel-heading" role="tab" id="headingOne">
                                        <h6 class="panel-title">
                                            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#@ipsection.value.ImpactArea.Substring(0, 3).Replace(" ", "")_@ipsection.i" aria-expanded="false" aria-controls="@ipsection.value.ImpactArea.Substring(0, 3).Replace(" ", "")_@ipsection.i">
                                                @ipsection.value.ImpactArea
                                            </a>
                                        </h6>
                                    </div>
                                    <div id="@ipsection.value.ImpactArea.Substring(0, 3).Replace(" ", "")_@ipsection.i" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                                        <div class="panel-body">
                                            @foreach (var ipsec in inp.BestPractices)
                                            {
                                                if (ipsec.ImpactArea == ipsection.value.ImpactArea)
                                                {
                                                    foreach (var checklist in ipsec.Checklist)
                                                    {
                                                        <div class="form-group row col-md-12" style="display: flex; margin-bottom: 0.1rem;">
                                                            <label class="control-label col-md-12">
                                                                <b>@checklist.Title</b>

                                                                <p class="practicedesp">
                                                                    @{
                                                                        Regex r = new Regex(@"(https?://[^\s]+)");
                                                                        var myString = r.Replace(checklist.Description, "<a href=\"$1\" style=\"color: #0366d6;\">$1</a>");
                                                                    }
                                                                    @Html.Raw(myString)
                                                                </p>

                                                                @*@if (checklist.Description != "")
                                                                    {
                                                                    <i class="fa fa-info-circle" aria-hidden="true" title="@checklist.Description"></i>
                                                                    }*@
                                                            </label>
                                                            <div class="col-md-6">
                                                                @{
                                                                    var comp = new Models.Computation();
                                                                    comp.Service = mod.value.Services;
                                                                    comp.ImpactArea = ipsection.value.ImpactArea;
                                                                    comp.Title = checklist.Title;
                                                                    comp.Description = checklist.Description;
                                                                    comp.Field = checklist.DisplayAttributes.Field;
                                                                    comp.Mandatory = checklist.DisplayAttributes.Mandatory;
                                                                    comp.ListOfValues = checklist.DisplayAttributes.ListOfValues;
                                                                    comp.Value = checklist.Input.Value;
                                                                    comp.disable = displaymode;
                                                                }
                                                                @await Html.PartialAsync("VW_DISPLAY_ATTRIBUTES", comp)
                                                            </div>
                                                            @{
                                                                var displayatt = "none";
                                                                if (checklist.Input.Value != "Required – Implemented" && checklist.Input.Value != "")
                                                                {
                                                                    displayatt = "block";
                                                                }
                                                            }
                                                            <div class="col-md-6 checklisttextbox" style="display:@displayatt;">
                                                                @{
                                                                    var inputcomp = new Models.Computation();
                                                                    inputcomp.Service = mod.value.Services;
                                                                    inputcomp.ImpactArea = ipsection.value.ImpactArea;
                                                                    inputcomp.Title = checklist.Title;
                                                                    inputcomp.Description = checklist.Description;
                                                                    inputcomp.Field = "TextArea";
                                                                    inputcomp.Mandatory = checklist.DisplayAttributes.Mandatory;
                                                                    inputcomp.ListOfValues = checklist.DisplayAttributes.ListOfValues;
                                                                    inputcomp.Value = checklist.Input.Remarks;
                                                                    inputcomp.disable = disabledmode;
                                                                }
                                                                @await Html.PartialAsync("VW_DISPLAY_ATTRIBUTES", inputcomp)
                                                            </div>
                                                        </div>
                                                        <hr class="solid">
                                                    }
                                                }

                                            }
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }

                    }
                }
            </div>
        }
    </div>
}
else
{
    <div> No Services to Display</div>
}
<script type="text/javascript">
    $(document).ready(function () {
        $(".form-control.selectpicker.checklistddl").change(function () {
            debugger;
            var ddlval = $(this).val();
             var textbox=$(this).parent().next();
            if(ddlval!="Required – Implemented"){
                $(textbox).show();
            }
            else{
                 $(textbox).hide();
            }
        });
     });
</script>

MicrofyWebApp/Views/Shared/VW_CHECKLIST_SUMMARY.cshtml
@model MicrofyWebApp.Models.Summary
<div class="form-card">
    <div class="row col-md-12">
        <div class="col-md-10"></div>
        <div class="col-md-2">
            <input type="button" name="print preview" onclick="@("window.location.href='" + @Url.Action("ViewAudit", "Application", new { projectname=Model.projectname,customername=Model.customername  }) + "' ");" class="print action-button btn btn-primary" value="Print Preview" />
        </div>
    </div>

    <div class="col-md-12 row justify-content">
        <div class="col-md-12" style="display: inline-flex;">
            <img src="~/Image/success.png" class="fit-image pull-right" style="width: 5%;">
            <h5 style="margin-top: 8px;">Thanks for providing inputs for @Model.projectname </h5>
        </div>
    </div><br />
    <div>
        <ul style="list-style-type:none;">
            <li>
                <h6>Here is the summary on how the Application aligns to best practices and recommendations:</h6><br />
                <ol style="list-style-type:none;">
                    <li>
                        <div class="col-md-12" style="display: inline-flex;">
                            <img src="https://img.icons8.com/color/96/000000/ok--v2.png" class="fit-image pull-right" style="width: 5%;">&nbsp;&nbsp;&nbsp;&nbsp;
                            <h6 style="margin-top: 8px;">Best Practices Implemented : @Model.RequiredCount</h6>
                        </div>
                    </li>
                    <li>
                        <div class="col-md-12" style="display: inline-flex;">
                            <img src="https://img.icons8.com/emoji/344/cross-mark-emoji.png" class="fit-image pull-right" style="width: 5%;"> &nbsp;&nbsp;&nbsp;&nbsp;
                            <h6 style="margin-top: 8px;">Best Practices Not Implemented : @Model.NotImplementedCount</h6>
                        </div>
                    </li>
                    <li>
                        <div class="col-md-12" style="display: inline-flex;">
                            <img src="https://img.icons8.com/small/344/visible.png" class="fit-image pull-right" style="width: 5%;"> &nbsp;&nbsp; &nbsp;&nbsp;
                            <h6 style="margin-top: 8px;">Observation Recorded : @Model.ObservationCount</h6>
                        </div>
                    </li>
                    <li>
                        <div class="col-md-12" style="display: inline-flex;">
                            <img src="~/Image/actionitems.png" class="fit-image pull-right" style="width: 5%;"> &nbsp;&nbsp;&nbsp;&nbsp;
                            <h6 style="margin-top: 8px;">Actionable Items : @Model.ActionItemsCount</h6>
                        </div>
                    </li>
                </ol>
            </li>

        </ul>
    </div>
</div>

MicrofyWebApp/Views/Shared/VW_DISPLAY_ATTRIBUTES.cshtml
@model MicrofyWebApp.Models.Computation
@{
    string[] dropval = Model.ListOfValues.Split(",");
}

@if (Model.Field == "Dropdown")
{
    if (Model.Value == "" || Model.Value == null)
    {
        <select class="form-control selectpicker checklistddl" @Model.disable data-service="@Model.Service" data-impactArea="@Model.ImpactArea" data-title="@Model.Title" data-description="@Model.Description" data-field="@Model.Field" data-mandatory="@Model.Mandatory" data-listOfValues="@Model.ListOfValues" data-value="@Model.Value">
            <option value="">Select</option>
            @foreach (var val in dropval)
            {
                <option value="@val">@val</option>
            }
        </select>
    }
    else
    {
        <select class="form-control selectpicker checklistddl" @Model.disable data-service="@Model.Service" data-impactarea="@Model.ImpactArea" data-title="@Model.Title" data-description="@Model.Description" data-field="@Model.Field" data-mandatory="@Model.Mandatory" data-listOfValues="@Model.ListOfValues" data-value="@Model.Value">
            <option value="">Select</option>
            @foreach (var val in dropval)
            {
                if (val == Model.Value)
                {
                    <option value="@val" selected>@val</option>
                }
                else
                {
                    <option value="@val">@val</option>
                }
            }
        </select>
    }
}

@if (Model.Field == "TextBox")
{
    if (Model.Value == "" || Model.Value == null)
    {
        <input class="form-control" placeholder="Enter Remarks" @Model.disable data-service="@Model.Service" data-impactArea="@Model.ImpactArea" data-title="@Model.Title" data-description="@Model.Description" data-field="@Model.Field" data-mandatory="@Model.Mandatory" data-listOfValues="@Model.ListOfValues" data-value="@Model.Value" />
    }
    else
    {
        <input class="form-control" placeholder="Enter Remarks" @Model.disable data-service="@Model.Service" data-impactArea="@Model.ImpactArea" data-title="@Model.Title" data-description="@Model.Description" data-field="@Model.Field" data-mandatory="@Model.Mandatory" data-listOfValues="@Model.ListOfValues" data-value="@Model.Value" value="@Model.Value" />

    }
}

@if (Model.Field == "TextArea")
{
    if (Model.Value == "" || Model.Value == null)
    {
        <textarea class="form-control" placeholder="Enter Remarks"  @Model.disable data-service="@Model.Service" data-impactArea="@Model.ImpactArea" data-title="@Model.Title" data-description="@Model.Description" data-field="@Model.Field" data-mandatory="@Model.Mandatory" data-listOfValues="@Model.ListOfValues" data-value="@Model.Value"></textarea>
    }
    else
    {
        <textarea class="form-control" placeholder="Enter Remarks"  @Model.disable data-service="@Model.Service" data-impactArea="@Model.ImpactArea" data-title="@Model.Title" data-description="@Model.Description" data-field="@Model.Field" data-mandatory="@Model.Mandatory" data-listOfValues="@Model.ListOfValues" data-value="@Model.Value" >@Model.Value</textarea>

    }
}