MicrofyWebApp/Controllers/RepositoryController.cs
using MicrofyWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.IO;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Reflection.Metadata;
using System.Text;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.AspNetCore.Authorization;
using System.Net;
using Microsoft.Extensions.Configuration;
using System.Web;

namespace MicrofyWebApp.Controllers
{
    public class RepositoryController : Controller
    {
        private readonly ILogger<RepositoryController> _logger;
        private IMemoryCache _cache;

        string Docurl = string.Empty;
        string Asseturl = string.Empty;
        string ConfigUrl = string.Empty;
        string DocCode = string.Empty;
        string AssetCode = string.Empty;
        string ConfigCode = string.Empty;
        string Activityurl = string.Empty;
        string ActivityCode = string.Empty;
        string userid = string.Empty;
        string Searchurl = string.Empty;
        string SearchCode = string.Empty;
        private IConfiguration _configuration;
        string Userurl = string.Empty;
        string Usercode = string.Empty;
        string ApplicationContainer = string.Empty;
        string DocumentContainer = string.Empty;

        public RepositoryController(ILogger<RepositoryController> logger, IMemoryCache memoryCache, IConfiguration configuration)
        {
            _logger = logger;
            _cache = memoryCache;
            _configuration = configuration;
            Docurl = _configuration.GetValue<string>("Values:DocumentBaseUrl");
            DocCode = _configuration.GetValue<string>("Values:DocumentCode");
            Asseturl = _configuration.GetValue<string>("Values:AssetStrgeBaseUrl");
            AssetCode = _configuration.GetValue<string>("Values:AssetStrgeCode");
            ConfigUrl = _configuration.GetValue<string>("Values:ConfigBaseUrl");
            ConfigCode = _configuration.GetValue<string>("Values:ConfigCode");
            Activityurl = _configuration.GetValue<string>("Values:ActivityBaseUrl");
            ActivityCode = _configuration.GetValue<string>("Values:ActivityCode");
            Searchurl = _configuration.GetValue<string>("Values:SearchBaseUrl");
            SearchCode = _configuration.GetValue<string>("Values:SearchCode");
            Userurl = _configuration.GetValue<string>("Values:UsersBaseUrl");
            Usercode = _configuration.GetValue<string>("Values:UsersCode");
            DocumentContainer = _configuration.GetValue<string>("Values:DocumentContainer");
            ApplicationContainer = _configuration.GetValue<string>("Values:ApplicationContainer");

        }
        public async Task<IActionResult> DashboardAsync()
        {
            //string username = (string)_cache.Get("_UserId");
            userid = HttpContext.Session.GetString("_userId");
            if (userid == null)
            {
                return RedirectToAction("Login", "Login");
            }

            MenuViewModel PhaseModel = new MenuViewModel();
            DocumentViewModel documentModel = new DocumentViewModel();
            string Phase;
            string Requestapi = $"api/GetMenuListFunction?{ConfigCode}";
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(ConfigUrl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage Res = await client.GetAsync(Requestapi);
                if (Res.IsSuccessStatusCode)
                {
                    Phase = Res.Content.ReadAsStringAsync().Result;
                    PhaseModel = JsonConvert.DeserializeObject<MenuViewModel>(Phase);
                    documentModel = await GetDocumentListAsync();
                    PhaseModel.documentRepository = documentModel.documentRepository;
                    PhaseModel.UserRole = HttpContext.Session.GetString("_UserRole");

                }
            }
            HttpContext.Session.SetString("_selPhase", "Dashboard");
            HttpContext.Session.SetString("_selSubPhase", string.Empty);
            return View(PhaseModel);
        }

        public async Task<IActionResult> RepositoryAsync(string menulevel1, string menulevel2)
        {
            DocumentViewModel DocModel = new DocumentViewModel();

            DocModel = await GetDocumentListAsync();
            if (menulevel2 == "" || menulevel2 == string.Empty || menulevel2 == null)
            {
                menulevel2 = string.Empty;
            }
            DocModel.selectedPhase = menulevel1;
            DocModel.selectedSubPhases = menulevel2;
            DocModel.UserRole = HttpContext.Session.GetString("_UserRole");
            HttpContext.Session.SetString("_selPhase", menulevel1);
            HttpContext.Session.SetString("_selSubPhase", menulevel2);

            return View(DocModel);
        }

        [HttpPost]
        public async Task<FileUploadResponse> UploadAsync(string flag, string phase, string subphase, IFormFile file, string tags, string displaytags)
        {
            string Container = string.Empty;
            if (flag == "Document")
            {
                Container = "containername=" + DocumentContainer;
            }
            else if (flag == "Application")
            {
                Container = "containername=" + ApplicationContainer;
            }
            using (var client = new HttpClient())
            {
                byte[] data;
                string Phase = "Phase=" + Encoder(phase);
                string SubPhase = "SubPhase=" + Encoder(subphase);
                string Requestapi = $"api/Upload?{AssetCode}&{Phase}&{SubPhase}&{Container}";
                FileUploadResponse FileUploadReponseValue = new FileUploadResponse();

                using (var br = new BinaryReader(file.OpenReadStream()))
                {
                    data = br.ReadBytes((int)file.OpenReadStream().Length);
                    ByteArrayContent bytes = new ByteArrayContent(data);
                    MultipartFormDataContent multiContent = new MultipartFormDataContent();
                    multiContent.Add(bytes, "file", file.FileName);
                    client.BaseAddress = new Uri(Asseturl);
                    client.DefaultRequestHeaders.Add("DisplayTags", displaytags);
                    client.DefaultRequestHeaders.Add("UserTags", tags);
                    var response = client.PostAsync(Requestapi, multiContent).Result;
                    if (response.IsSuccessStatusCode)
                    {
                        FileUploadReponseValue.statuscode = response.IsSuccessStatusCode;
                        FileUploadReponseValue.url = await response.Content.ReadAsStringAsync();
                        //bool Activity = ActivityTracker("UploadDocument", $"New Document uploaded in url {FileUploadReponseValue.url}");

                    }
                    else
                    {
                        FileUploadReponseValue.statuscode = response.IsSuccessStatusCode;
                        FileUploadReponseValue = JsonConvert.DeserializeObject<FileUploadResponse>(await response.Content.ReadAsStringAsync());

                    }
                    return FileUploadReponseValue;

                }
            }

        }

        [HttpPost]
        public async Task<ActionResult> CreateDocumentAsync(CreateDocuments create)
        {
            DocumentViewModel DocModel = new DocumentViewModel();

            create.UploadedOn = DateTime.Now.ToString("dd/MM/yyyy");
            create.UploadedBy = HttpContext.Session.GetString("_username");

            var createDoc = JsonConvert.SerializeObject(create);
            string Requestapi = $"api/Document?{DocCode}";

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Docurl);
                var result = client.PostAsync(Requestapi, new StringContent(JsonConvert.SerializeObject(create), Encoding.UTF8, "application/json")).Result;
                if (result.IsSuccessStatusCode)
                {
                    _cache.Remove("_GetDocList");
                    DocModel = await GetDocumentListAsync();
                    DocModel.selectedPhase = create.Phase;
                    DocModel.selectedSubPhases = create.SubPhase;
                    DocModel.UserRole = HttpContext.Session.GetString("_UserRole");
                    userid = HttpContext.Session.GetString("_userId");
                    //bool Activity = ActivityTracker("NewDocument", $"User {userid} has posted a new document {Path.GetFileName(create.URL)} at {create.URL}");
                }
            }
            return PartialView("VW_Document_Repos_Partial", DocModel);

        }



        [HttpGet]
        public async Task<ActionResult> GetDocumentRepositoryAsync(string Phase, string SubPhase)
        {
            DocumentViewModel DocModel = new DocumentViewModel();

            DocModel = await GetDocumentListAsync();

            DocModel.selectedPhase = Phase;
            DocModel.selectedSubPhases = SubPhase;
            DocModel.UserRole = HttpContext.Session.GetString("_UserRole");

            return PartialView("VW_Document_Repos_Partial", DocModel);
        }

        public async Task<DocumentViewModel> GetDocumentListAsync()
        {
            string DocRepos = string.Empty;
            DocumentViewModel DocModel = new DocumentViewModel();
            string Requestapi = $"api/Get?{DocCode}";

            if (!_cache.TryGetValue("_GetDocList", out DocRepos))
            {
                using (var client = new HttpClient())
                {

MicrofyWebApp/Views/Login/Login.cshtml
@{
    Layout = "";
    ViewData["Title"] = "Login";

}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Welcome to Cumulus</title>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/login.css" />

</head>
<body>
    @*<div class="body">

    </div>
    <div class="grad"></div>*@
    @*<div class="header">
    <div class="imglogo">
    <img id="img_logo" alt="Logo" src="~/Image/Cumulus.png" />
    </div>
    </div>*@

    @*@using (Html.BeginForm("Dashboard", "Repository", FormMethod.Post, new { enctype = "multipart/form-data" })) *@
    @*<input type="text" id="txtuname" placeholder="Enter Username" name="uname" required><br>
    <input type="password" id="txtpwd" placeholder="Enter Password" name="psw" required><br>*@

    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-2"></div>
            <div class="col-lg-6 col-md-8 login-box">
                <div class="col-lg-12 login-key">
                    <div class="imglogo">
                        <img id="img_logo" alt="Logo" src="/Image/Cumulus.png">
                    </div>
                </div>
                <div class="col-lg-12 login-form">
                    <div class="col-lg-12 login-form">
                        <div class="form-group">
                            @*<label class="form-control-label">USERNAME</label>*@
                            <input type="text" id="txtuname" placeholder="Enter Username" name="uname" required class="form-control login">
                        </div>
                        <div class="form-group">
                            @*<label class="form-control-label">PASSWORD</label>*@
                            <input type="password" id="txtpwd" placeholder="Enter Password" name="psw" required class="form-control login">
                        </div>

                        <div class="col-lg-12 loginbttm">
                            <div class="col-lg-8 login-btm login-text">
                                <p>Don't have an account? &nbsp;<a href="/Login/Registration">Sign up</a></p>
                            </div>
                            <div class="col-lg-4 login-btm login-button">
                                <input type="submit" id="btnsubmit" class="btn btn-outline-primary login" value="Login">
                            </div>
                        </div>
                    </div>
                </div>
                <p id="ResponseMessage" style="color:red;"></p>
            </div>
        </div>

        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>

    </div>
</body>
</html>
<script type="text/javascript">

    $(document).ready(function() {
        $('#btnsubmit').click(function(e) {
            e.preventDefault();
            $('#ResponseMessage').html("");
            var Username = $('#txtuname').val();
            var Password = $('#txtpwd').val();
            if (Username == "") {
                $('#ResponseMessage').html("Enter UserName");
                return false;
            }
            if (Password == "") {
                $('#ResponseMessage').html("Enter Password");
                return false;
            }
            var redirecturl = "/Login/UserLogin";
            var loginDetails = {
                UserId: Username,
                Password: Password
            }
            $.post(redirecturl, loginDetails, function(data) {
                debugger;
                if (data.statusCode == true) {
                    $('#ResponseMessage').html("");
                    if (data.moduleAccess.length > 0) {
                        $.each(data.moduleAccess, function(i, value) {
                            if (value.name == "Repository" && value.visible == "true")
                                window.location.href = '@Url.Action("Dashboard", "Repository")';
                            else
                                window.location.href = '@Url.Action("Application", "Application")';
                        });
                    }
                    else
                        window.location.href = '@Url.Action("Application", "Application")';
                }
                else {
                    $('#ResponseMessage').html(data.responseMessage);
                }

            });

        });
        $('.login').keypress(function(e) {
            if (e.which == 13) {//Enter key pressed
                $('#btnsubmit').click();
            }
        });
    });


</script>

MicrofyWebApp/Views/Login/Registration.cshtml
@{
    Layout = "";
    ViewData["Title"] = "SignUp";

}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Welcome to Cumulus</title>
    <link rel="stylesheet" href="~/lib/jquery/dist/css/jquery-confirm.css" />

    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style type="text/css">
        .input-group-addon {
            padding: 6px 20px !important;
        }
        /*.jconfirm .jconfirm-holder {*/
        /*max-height: 100%;*/
        /*padding-right: 250px !important;
        }*/
        .justify-content-lg-center {
            justify-content: left !important;
        }
    </style>
</head>
<body>
    <div class="container" style="padding-left:60px">
        <form class="well form-horizontal" action=" " method="post" id="Registration_form">
            <fieldset>
                <div class="imglogo" style="display:flex;">
                    <img id="img_logo" alt="Logo" src="~/Image/Cumulus.png" onclick="@("window.location.href='" + @Url.Action("Login", "Login") + "'");" />
                    <div class=" col-lg-8" style="padding-top:40px">
                        <center><h2><b>Sign-up</b></h2></center>
                    </div>
                </div>
                <!-- Form Name -->
                <!-- Text input-->

                <div class="form-group">
                    <label class="col-md-4 control-label"><span style="color:red;">*</span>  Full Name</label>
                    <div class="col-md-4 inputGroupContainer">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            <input name="first_name" id="first_name" placeholder="User Name" class="form-control" type="text" required>
                            <span data-alertid="first_name"></span>
                        </div>
                    </div>
                </div>



                @*<div class="form-group">
                        <label class="col-md-4 control-label"><span style="color:red;">*</span>  Project Name</label>
                        <div class="col-md-4 inputGroupContainer">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                <input name="project_name" id="project_name" placeholder="Project Name" class="form-control" type="text" required>
                            </div>
                        </div>
                    </div>*@


                <!--<div class="form-group">
                <label class="col-md-4 control-label">Role</label>
                <div class="col-md-4 selectContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>
                        <select name="role" id="role" class="form-control selectpicker" required>
                            <option value="">Select Role</option>
                            <option value="Administrator">Administrator</option>
                            <option value="User">User</option>-->
                @*<option>Auditor</option>*@
                <!--</select>
                        </div>
                    </div>
                </div>-->
                <!-- Text input-->

                <div class="form-group">
                    <label class="col-md-4 control-label"><span style="color:red;">*</span>  Userid</label>
                    <div class="col-md-4 inputGroupContainer">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                            <input name="userid" id="userid" placeholder="Userid" class="form-control" type="email" required>
                        </div>
                    </div>
                </div>

                <!-- Text input-->

                <div class="form-group">
                    <label class="col-md-4 control-label"><span style="color:red;">*</span>  Password</label>
                    <div class="col-md-4 inputGroupContainer">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                            <input name="user_password" type="password" id="user_password" title="Password must contain: Minimum 8 characters atleast 1 Alphabet and 1 Number"
                                   class="form-control" placeholder="Enter Password" required />
                        </div>
                    </div>
                </div>

                <!-- Text input-->

                <div class="form-group">
                    <label class="col-md-4 control-label"><span style="color:red;">*</span>  Confirm Password</label>
                    <div class="col-md-4 inputGroupContainer">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                            <input name="confirm_password" id="confirm_password" placeholder="Confirm Password" class="form-control" required type="password">
                        </div>
                    </div>
                </div>


                <div class="form-group">
                    <label class="col-md-4 control-label"><span style="color:red;">*</span>  Project & Customer Name</label>
                    <div class="col-md-8 inputGroupContainer">
                        <div class="input-group">
                            @*<span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                <input name="cust_name" id="cust_name" placeholder="Customer Name" class="form-control" type="text" required>*@
                            <div id="dynamic-PrjCus-field-1" class=" col-md-12 form-group dynamic-field" style="display:flex;" data-tags="add">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                <input name="project_name" id="project_name-1" placeholder="Project Name" class="col-md-3 form-control" type="text" onkeydown="addprj($(this))" required>

                                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                <input name="cust_name" id="cust_name-1" placeholder="Customer Name" class="col-md-3 form-control" type="text" required>
                                <a href="#" class="add" title="Add Tags" style="padding:5px; display:block;" onclick="Viewprj(); return false;">
                                    <i class="fas fa-plus"></i>
                                </a>
                                <a href="#" class="delete" title="delete Tags" style="padding:5px; display:none;" onclick="deleteprj($(this)); return false;">
                                    <i class="fas fa-trash-alt"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>



                <!-- Select Basic -->
                <!-- Success message -->
                @*<div class="alert alert-success" role="alert" id="success_message">Success <i class="glyphicon glyphicon-thumbs-up"></i> Success!.</div>*@

                <!-- Button -->
                <div class="form-group">
                    <div class="col-md-4 control-label">
                        <button type="button" id="btnBack" onclick="@("window.location.href='" + @Url.Action("Login", "Login") + "'");" class="btn btn-warning"><span class="glyphicon glyphicon-arrow-left"></span> BACK</button>
                    </div>
                    <div class="col-md-4 control-label">
                        <button type="submit" class="btn btn-warning">SUBMIT <span class="glyphicon glyphicon-send"></span></button>
                    </div>
                </div>

            </fieldset>
        </form>
    </div>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery/dist/jquery-confirm.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>

</body>
</html>
<script type="text/javascript">
    window.onload = function () {
        var txtPassword = document.getElementById("user_password");
        var txtConfirmPassword = document.getElementById("confirm_password");
        txtPassword.onchange = ConfirmPassword;
        txtConfirmPassword.onkeyup = ConfirmPassword;
        function ConfirmPassword() {
            txtConfirmPassword.setCustomValidity("");
            if (txtPassword.value != txtConfirmPassword.value) {
                txtConfirmPassword.setCustomValidity("Passwords do not match.");
            }
        }
    }

$('#Registration_form').submit(function () {
    var username = $('#first_name').val();
    //var custname = $('#cust_name').val();
    //var projectname = $('#project_name').val();
    var role = "User"; //$('#role :selected').text();
    var userid = $('#userid').val();
    var password = $('#user_password').val();
    var confrmpassword = $('#confirm_password').val();

    var $projCus = $('.dynamic-field');
    var prj = [];
    $projCus.each(function (key, value) {
        var Proj = $("#project_name-" + (key + 1)).val();
        var Cust = $("#cust_name-" + (key + 1)).val();
        if (Proj != "") {
            var obj = {};
            obj = {
                "ProjectName": Proj,
                "CustomerName": Cust
            };
            prj.push(obj);
        }
    });

    //var Projects = [{
    //    "ProjectName": projectname,
    //    "CustomerName": custname
    //}];

    var UserDetails = {
        "username": userid,
        "password": password,
        "fullName": username,
        "userRole": role,
        "isActive": false,
        "projects": prj
    }

        var redirecturl = "/Login/signup";
    $.post(redirecturl, UserDetails, function (data) {

        var title = "";
            var type = "";
            if (data.statusCode == true) {
                title = "Success!!";
                type = "green";
            }
            else {
                title = "Error!!";
                type = "red";
            }
            $.alert({
                    title: title,
                    content: data.responseMessage +" \n Please contact Admin to Unlock your account!!!",
                    type: type,
                    onAction: function () {
                        window.location.href = '@Url.Action("Login","Login")';
                    }
                });
        })
        .fail(function (response) {
           $.alert({
                title: 'Error!!',
                content: response,
                alignMiddle: true,
                type: 'red'
            });
        });
    return false;


});
</script>
@*<script type="text/javascript">
    var prjclassName = ".dynamic-field";
    var prjcount = 0;
    var prjfield = "";
    var prjmaxFields = 5;

    function addprj(e) {
        if (prjtotalFields() != prjmaxFields) {
            if (e.parent().data('tags') === 'hold') { return false; }
            else { e.parent().data('tags', 'hold'); }
            prjcount = prjtotalFields() + 1;
            prjfield = $("#dynamic-PrjCus-field-1").clone();
            prjfield.attr("id", "dynamic-PrjCus-field-" + prjcount);
            prjfield.find("#cust_name-1").attr("id", "cust_name-" + prjcount);
            prjfield.find("#project_name-1").attr("id", "project_name-" + prjcount);
            prjfield.find('#cust_name-' + prjcount).removeAttr('required')
            prjfield.find('#project_name-' + prjcount).removeAttr('required')
            prjfield.attr('data-tags', 'add');
            prjfield.find("input").val("");
            prjfield.find("a.delete").show();
            $(prjclassName + ":last").after($(prjfield));

        }
    }

    function prjtotalFields() {
        return $(prjclassName).length;
    }

    function deleteprj(e) {
        e.parent().remove();
        prjcount = prjtotalFields();
        if (prjcount <= 1) { $(".dynamic-field").data('tags', 'add'); }
        else {
            $(prjclassName + ":last").data('tags', 'add')
        }
        return false;
    }

    function Viewprj() {
        if (prjtotalFields() != prjmaxFields) {
            prjcount = prjtotalFields() + 1;
            prjfield = $("#dynamic-PrjCus-field-1").clone();
            prjfield.attr("id", "dynamic-PrjCus-field-" + prjcount);
            //field.find("#txtkey-1").attr("id", "txtkey-" + count);
            prjfield.find("#cust_name-1").attr("id", "cust_name-" + prjcount);
            prjfield.find("#project_name-1").attr("id", "project_name-" + prjcount);
            prjfield.attr('data-tags', 'add');
            prjfield.find("input").val("");
            prjfield.find("a.delete").show();
            $(prjclassName + ":last").after($(prjfield));

        }
    }
</script>*@